(()=>{
 const host=document.querySelector('[data-profile-host]');
 host.innerHTML='<a href="/api/auth/authorize" hidden>Sign in</a><details hidden><summary aria-label="Profile" title="Profile"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></svg></summary><div><button type="button">Sign out</button></div></details><p role="status" hidden></p>';
 const menu=host.querySelector('details'),button=host.querySelector('button'),status=host.querySelector('p');let auth=null,busy=false;
 async function load(){if(busy)return;try{const r=await fetch('/api/auth/session',{cache:'no-store',signal:AbortSignal.timeout(12000)});if(r.status===401)auth=null;else if(r.ok)auth=await r.json();else throw Error();status.hidden=true;status.textContent='';menu.hidden=!auth;host.querySelector('a').hidden=!!auth;menu.querySelector('summary').setAttribute('aria-label',auth?`Profile: ${auth.user.name}`:'Profile');}catch{status.hidden=false;status.textContent='Account unavailable. Try again when connected.';}}
 button.onclick=async()=>{busy=true;button.disabled=true;try{const r=await fetch('/api/auth/signout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':auth.csrf},body:'{}'});if(!r.ok)throw Error();menu.open=false;window.dispatchEvent(new Event('study-account-change'));const frame=document.querySelector('#study-page');frame?.contentWindow.location.reload();}catch{status.hidden=false;status.textContent='Could not sign out. Please try again.';}finally{busy=false;button.disabled=false;await load();}};
 document.addEventListener('click',e=>{if(!menu.contains(e.target))menu.open=false;});menu.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.open=false;menu.querySelector('summary').focus();}});
 window.addEventListener('study-account-change',load);window.addEventListener('focus',load);window.addEventListener('online',load);load();
})();
